spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/artmarket?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp